repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
        args: [.]
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        pass_filenames: false
        args: [semtest, example_benchmarks, tests]
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [tests]